// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIkkZGq2XLU7fd3auno1eOgW4F9kT8l4',
    appId: '1:855889447188:web:d0207034eaea4a7361da01',
    messagingSenderId: '855889447188',
    projectId: 'booth-bliss',
    authDomain: 'booth-bliss.firebaseapp.com',
    storageBucket: 'booth-bliss.appspot.com',
    measurementId: 'G-6RJGNNDFX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJr9n4DvuxGW2No5VIKdracAANPgpNw1Y',
    appId: '1:855889447188:android:f49ea4c22a81c0f561da01',
    messagingSenderId: '855889447188',
    projectId: 'booth-bliss',
    storageBucket: 'booth-bliss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7F03HeFXSpI1o786K--PXBL3LXR-TFJ0',
    appId: '1:855889447188:ios:4ee58a45deee0eaf61da01',
    messagingSenderId: '855889447188',
    projectId: 'booth-bliss',
    storageBucket: 'booth-bliss.appspot.com',
    iosBundleId: 'com.example.boothBliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7F03HeFXSpI1o786K--PXBL3LXR-TFJ0',
    appId: '1:855889447188:ios:4ee58a45deee0eaf61da01',
    messagingSenderId: '855889447188',
    projectId: 'booth-bliss',
    storageBucket: 'booth-bliss.appspot.com',
    iosBundleId: 'com.example.boothBliss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIkkZGq2XLU7fd3auno1eOgW4F9kT8l4',
    appId: '1:855889447188:web:f5f7cb19c463ee6161da01',
    messagingSenderId: '855889447188',
    projectId: 'booth-bliss',
    authDomain: 'booth-bliss.firebaseapp.com',
    storageBucket: 'booth-bliss.appspot.com',
    measurementId: 'G-VW6M062R7Z',
  );

}